# Rails/Postgres Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: urls-env-config
data:
  CORONA_ENV: production
  DATABASE_ADAPTER: postgresql
  DATABASE_USER: user
  DATABASE_DATABASE: recario_urls
  DATABASE_MAX_CONNECTIONS: "5"
  RECARIO_API_HOST: https://recar.io
  # Secrets
  RECARIO_API_TOKEN: ${RECARIO_API_TOKEN}
  DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
